## Tensors

In [1]:
a = [1.0, 2.0, 1.0]

In [2]:
a[0]

1.0

In [3]:
a[2] = 3.0

In [4]:
a

[1.0, 2.0, 3.0]

In [5]:
import torch

In [6]:
a = torch.ones(3)

In [7]:
a

tensor([1., 1., 1.])

In [8]:
a[1]

tensor(1.)

In [9]:
float(a[1])

1.0

In [10]:
a[2] = 2.0

In [11]:
a

tensor([1., 1., 2.])

In [12]:
points = torch.zeros(6)
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0

In [13]:
points = torch.tensor([4.0,1.0,5.0,3.0,2.0,1.0])

In [14]:
points

tensor([4., 1., 5., 3., 2., 1.])

In [15]:
float(points[0]),float(points[1])

(4.0, 1.0)

In [16]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [17]:
points.shape

torch.Size([3, 2])

In [19]:
points = torch.zeros(3,2)
points

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [20]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [21]:
points[0,1]

tensor(1.)

In [22]:
points[0]

tensor([4., 1.])

## Indexing Tensors

In [23]:
some_list = list(range(6))

In [24]:
some_list[:]

[0, 1, 2, 3, 4, 5]

In [25]:
some_list[1:4]

[1, 2, 3]

In [26]:
some_list[1:]

[1, 2, 3, 4, 5]

In [27]:
some_list[:4]

[0, 1, 2, 3]

In [28]:
some_list[:-1]

[0, 1, 2, 3, 4]

In [29]:
some_list[1:4:2]

[1, 3]

In [30]:
points[1:]

tensor([[5., 3.],
        [2., 1.]])

In [31]:
points[1:,:]

tensor([[5., 3.],
        [2., 1.]])

In [32]:
points[1:,0]

tensor([5., 2.])

In [33]:
points[None]

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

## Named Tensors

In [34]:
img_t = torch.randn(3,5,5)
weights = torch.tensor([0.2126,0.7152,0.0722])

In [35]:
batch_t = torch.randn(2,3,5,5)

In [36]:
img_gray_naive = img_t.mean(-3)
batch_gray_naive = batch_t.mean(-3)
img_gray_naive.shape, batch_gray_naive.shape

(torch.Size([5, 5]), torch.Size([2, 5, 5]))

In [46]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze_(-1)

In [47]:
img_weights = (img_t * unsqueezed_weights)

In [50]:
batch_weights = (batch_t * unsqueezed_weights)

In [51]:
img_gray_weighted = img_weights.sum(-3)

In [53]:
batch_gray_weighted = batch_weights.sum(-3)

In [54]:
batch_weights.shape, batch_t.shape, unsqueezed_weights.shape

(torch.Size([2, 3, 5, 5]), torch.Size([2, 3, 5, 5]), torch.Size([3, 1, 1]))

In [56]:
img_gray_weighted_fancy = torch.einsum('...chw,c->...hw',img_t,weights)

In [57]:
batch_gray_weighted_fancy = torch.einsum('...chw,c->...hw',batch_t, weights)

In [58]:
batch_gray_weighted_fancy.shape

torch.Size([2, 5, 5])

In [59]:
weights_named = torch.tensor([0.2126,0.7152,0.0722],names=['channels'])
weights_named

C:\Users\jnrah\AppData\Local\Temp\ipykernel_12432\1804826620.py:1: UserWarning: Named tensors and all their associated APIs are an experimental feature and subject to change. Please do not use them for anything important until they are released as stable. (Triggered internally at  C:\cb\pytorch_1000000000000\work\c10/core/TensorImpl.h:1463.)
  weights_named = torch.tensor([0.2126,0.7152,0.0722],names=['channels'])


tensor([0.2126, 0.7152, 0.0722], names=('channels',))

In [60]:
img_named = img_t.refine_names(...,'channels','rows','columns')
batch_named = batch_t.refine_names(...,'channels','rows','columns')
print("img_named : ",img_named.shape,img_named.names)
print("batch_named : ",batch_named.shape, batch_named.names)

img_named :  torch.Size([3, 5, 5]) ('channels', 'rows', 'columns')
batch_named :  torch.Size([2, 3, 5, 5]) (None, 'channels', 'rows', 'columns')


In [61]:
weights_aligned = weights_named.align_as(img_named)
weights_aligned.shape, weights_aligned.names

(torch.Size([3, 1, 1]), ('channels', 'rows', 'columns'))

In [63]:
gray_named = (img_named * weights_aligned).sum('channels')

In [64]:
gray_named.shape, gray_named.names

(torch.Size([5, 5]), ('rows', 'columns'))

In [65]:
gray_plain = gray_named.rename(None)
gray_plain.shape, gray_plain.names

(torch.Size([5, 5]), (None, None))

## Tensor element types

In [66]:
double_points = torch.ones(10,2,dtype = torch.double)

In [67]:
short_points = torch.tensor([[1,2],[3,4]],dtype = torch.short)

In [68]:
short_points.dtype

torch.int16

In [69]:
double_points = torch.zeros(10,2).double()

In [70]:
short_points = torch.ones(10,2).short()

In [71]:
double_points = torch.zeros(10,2).to(torch.double)

In [72]:
short_points = torch.zeros(10,2).to(torch.short)

In [73]:
points_64 = torch.rand(5, dtype = torch.double)

In [74]:
points_short = points_64.to(torch.short)

In [75]:
points_short * points_64

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

## Tensor API

In [76]:
a = torch.ones(3,2)

In [77]:
a_t = torch.transpose(a,0,1)

In [78]:
a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [79]:
a_t = a.transpose(0,1)

In [80]:
a_t.shape

torch.Size([2, 3])

## Tensor Storage

In [81]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [82]:
points.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.FloatStorage of size 6]

In [83]:
points.storage()[1]

1.0

In [84]:
a = torch.ones(3,2)

In [85]:
a.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [86]:
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Tensor Metadata

In [87]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [88]:
second_point = points[1]

In [89]:
second_point.storage_offset()

2

In [90]:
second_point.size()

torch.Size([2])

In [92]:
second_point.shape

torch.Size([2])

In [93]:
points.stride()

(2, 1)

In [94]:
second_point.stride()

(1,)

In [95]:
second_point[0] = 10.0

In [96]:
points

tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [97]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [101]:
points = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]])

In [102]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [103]:
id(points.storage()) == id(points_t.storage())

False

In [107]:
points.stride()

(2, 1)

In [108]:
points_t.stride()

(1, 2)

In [109]:
some_t = torch.ones(3,4,5)
transpose_t = some_t.transpose(0,2)
some_t.shape, transpose_t.shape

(torch.Size([3, 4, 5]), torch.Size([5, 4, 3]))

In [110]:
id(some_t.storage()) == id(transpose_t.storage())

False

In [111]:
some_t.stride()

(20, 5, 1)

In [112]:
transpose_t.stride()

(1, 5, 20)

In [113]:
points.is_contiguous()

True

In [114]:
points_t.is_contiguous()

False

In [115]:
points_t_cont = points_t.contiguous()

In [116]:
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [117]:
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [118]:
points_t.stride(), points_t_cont.stride()

((1, 2), (3, 1))

In [119]:
id(points_t.storage()) == id(points_t_cont.storage())

False

## Moving Tensors to GPU

In [120]:
torch.cuda.is_available()

True

In [121]:
points_gpu = torch.tensor([[4.0,1.0],[5.0,3.0],[2.0,1.0]], device='cuda')

In [122]:
points_gpu = points.to(device = 'cuda')

In [123]:
points_gpu = points.to(device = 'cuda:0')

In [124]:
points = 2 * points

In [125]:
points_gpu = 2 * points.to(device = 'cuda')

In [126]:
points_gpu = points_gpu + 4

In [127]:
points_cpu = points_gpu.to(device = 'cpu')

## Numpy Interoperability

In [128]:
points = torch.ones(3,4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [129]:
points = torch.from_numpy(points_np)

## Serializing Tensors

In [130]:
torch.save(points, 'git_rep/data/p1ch3/ourpoints.t')

In [133]:
import h5py

In [134]:
f = h5py.File("git_rep/data/p1ch3/ourpoints.hdf5",'w')

In [135]:
dset = f.create_dataset('coords',data=points.numpy())

In [136]:
f.close()

In [137]:
f = h5py.File("git_rep/data/p1ch3/ourpoints.hdf5","r")

In [138]:
dset = f['coords']

In [139]:
last_points = dset[-2:]

In [141]:
last_points

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [142]:
last_points = torch.from_numpy(dset[-2:])

In [143]:
f.close()

## Exercises

In [144]:
a = torch.tensor(list(range(9)))

In [145]:
a.size()

torch.Size([9])

In [146]:
a.stride()

(1,)

In [147]:
a.storage_offset()

0

In [148]:
b = a.view(3,3)

In [149]:
b

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [150]:
id(a.storage()) == id(b.storage())

False

In [151]:
c = b[1:,1:]

In [152]:
c.shape

torch.Size([2, 2])

In [153]:
c.stride()

(3, 1)

In [154]:
c.storage_offset()

4

In [155]:
b.stride()

(3, 1)

In [156]:
torch.cos(a)

tensor([ 1.0000,  0.5403, -0.4161, -0.9900, -0.6536,  0.2837,  0.9602,  0.7539,
        -0.1455])

In [157]:
a**0.5

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])

In [159]:
torch.sqrt(a)

tensor([0.0000, 1.0000, 1.4142, 1.7321, 2.0000, 2.2361, 2.4495, 2.6458, 2.8284])